WEBHOOK_URL = "https://connect.pabbly.com/workflow/sendwebhookdata/IjU3NjUwNTY0MDYzZTA0MzE1MjY0NTUzMzUxMzIi_pc"

openai_key = "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"